server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_test?autoReconnect=true&useSSL=false
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
  redis:
    host: 10.20.11.24
    port: 6379