server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_test?autoReconnect=true&useSSL=false
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
  cache:
    jcache:
      config: config/ehcache3.xml
  output:
    ansi:
      enabled: detect
logging:
  level:
    org.ehcache: debug
